import * as XLSX from 'xlsx';
import {
  INITIAL_RAW_DATA,
  INITIAL_RATE_CARD_4W,
  INITIAL_RATE_CARD_6W,
  INITIAL_RATE_CARD_10W,
  INITIAL_RATE_CARD_OD4,
  INITIAL_RATE_CARD_OD6,
  INITIAL_DIESEL_PRICES,
  INITIAL_QUOTATIONS,
} from '../data/seedData';
import { RawTripData } from '../types';

export interface SampleFileInfo {
  id: string;
  name: string;
  category: 'raw_trips' | 'quotation' | 'rate_card' | 'diesel';
  description: string;
  sizeStr: string;
  recordCount: number;
  format: 'xlsx';
  tags: string[];
}

export const SAMPLE_FILES_CATALOG: SampleFileInfo[] = [
  {
    id: 'sample-trips-sep2026',
    name: 'Transportation_Raw_Trips_Sep2026.xlsx',
    category: 'raw_trips',
    description: 'ชุดข้อมูลเที่ยวรถดิบ 20 รายการ นวนคร/บางบ่อ มีทั้งรถบริษัทและรถซับ OD (AJITRADE, SIEMENS, TOYOTA)',
    sizeStr: '18.5 KB',
    recordCount: 20,
    format: 'xlsx',
    tags: ['เที่ยวรถดิบ', 'เดือนกันยายน 2026', 'รถบริษัท & OD', 'สาขานวนคร & บางบ่อ'],
  },
  {
    id: 'sample-quotations-template',
    name: 'Quotation_Master_Template_2026.xlsx',
    category: 'quotation',
    description: 'ไฟล์ต้นแบบใบเสนอราคาโครงสร้างค่าบริการ ค่าดรอป ค่ารอ ค่าทางด่วน ค่าคนยก สำหรับ AI OCR',
    sizeStr: '14.2 KB',
    recordCount: 5,
    format: 'xlsx',
    tags: ['ใบเสนอราคา', 'AI OCR Parser', 'ค่าดรอป & ค่ารอ', 'เรทรถซับ OD'],
  },
  {
    id: 'sample-ratecard-standard',
    name: 'RateCard_Standard_16Brackets.xlsx',
    category: 'rate_card',
    description: 'ตาราง Rate Card มาตรฐานรถ 4W, 6W, 10W ครอบคลุม 16 ช่วงราคาน้ำมัน (30.01 - 60.00 บาท)',
    sizeStr: '22.8 KB',
    recordCount: 54,
    format: 'xlsx',
    tags: ['Rate Card', '16 Brackets', '4W / 6W / 10W', 'โซนนิคมอุตสาหกรรม'],
  },
  {
    id: 'sample-diesel-ptt-sep2026',
    name: 'PTT_Diesel_Database_Sep2026.xlsx',
    category: 'diesel',
    description: 'ฐานข้อมูลราคาน้ำมันดีเซล ปตท. รายวัน 1-30 ก.ย. 2026 เฉลี่ย 40.69 บาท/ลิตร (แก้ปัญหา Diff)',
    sizeStr: '11.0 KB',
    recordCount: 30,
    format: 'xlsx',
    tags: ['ราคาน้ำมัน ปตท.', 'Monthly Average 40.69', '30 วันเต็ม', 'ดีเซล B7'],
  },
];

/**
 * Generate and trigger direct browser download of Sample Raw Trips Excel
 */
export function downloadSampleTripsExcel(tripsData: RawTripData[] = INITIAL_RAW_DATA) {
  const wb = XLSX.utils.book_new();

  const headers = [
    'Issue Date',
    'Job No.',
    'Trip No.',
    'Branch',
    'OD Type',
    'Consignee/Shipper',
    'Pick Up Name',
    'Pick Up District',
    'Pick Up Province',
    'Delivery Name',
    'Delivery District',
    'Delivery Province',
    'Delivery Zone',
    'Truck Type',
    'Trip Status',
    'Haul Type',
    'Backhaul',
    'Customer Quoted Rate (THB)',
  ];

  const rows = tripsData.map((t, idx) => [
    t.issueDate || '1/9/2026',
    t.jobNo || `2609000${idx + 1}`,
    t.tripNo || `TRP-2609-${String(idx + 1).padStart(3, '0')}`,
    t.branch || (idx % 2 === 0 ? 'นวนคร' : 'บางบ่อ'),
    t.odType || (idx % 3 === 0 ? 'OD 4' : idx % 3 === 1 ? 'Company Truck' : 'OD 6'),
    t.consigneeShipper,
    t.pickUpName,
    t.pickUpDistrict,
    t.pickUpProvince,
    t.deliveryName,
    t.deliveryDistrict,
    t.deliveryProvince,
    t.deliveryZone,
    t.truckType,
    t.tripStatus,
    t.haulType,
    t.backhaul,
    t.truckType.includes('4W') ? 3280 : t.truckType.includes('6W') ? 4500 : 6200,
  ]);

  const ws = XLSX.utils.aoa_to_sheet([headers, ...rows]);
  ws['!cols'] = [
    { wch: 12 }, { wch: 14 }, { wch: 16 }, { wch: 10 }, { wch: 14 },
    { wch: 32 }, { wch: 30 }, { wch: 16 }, { wch: 16 },
    { wch: 30 }, { wch: 18 }, { wch: 18 }, { wch: 18 },
    { wch: 16 }, { wch: 12 }, { wch: 12 }, { wch: 10 }, { wch: 20 },
  ];

  XLSX.utils.book_append_sheet(wb, ws, 'Raw_Trips_Data');
  XLSX.writeFile(wb, 'Transportation_Raw_Trips_Sep2026.xlsx');
}

/**
 * Generate and trigger download of Quotation Master Template
 */
export function downloadQuotationTemplateExcel() {
  const wb = XLSX.utils.book_new();

  const headers = [
    'Company Name',
    'Branch',
    'Effective Date',
    'Expiry Date',
    '4W Base Rate',
    '6W Base Rate',
    '10W Base Rate',
    'OD 4 Rate',
    'OD 6 Rate',
    'OD 10 Rate',
    'Drop Fee Per Point',
    'Waiting Fee Per Hour',
    'Toll Fee',
    'Porter Fee',
    'Dry Ice Fee',
    'Special Conditions',
  ];

  const rows = INITIAL_QUOTATIONS.map((q) => [
    q.companyName,
    q.branch,
    q.effectiveDate,
    q.expiryDate,
    q.truckTypes['4W']?.baseRate || 3200,
    q.truckTypes['6W']?.baseRate || 4500,
    q.truckTypes['10W']?.baseRate || 6800,
    q.odRates?.['OD4']?.baseRate || 2900,
    q.odRates?.['OD6']?.baseRate || 4100,
    q.odRates?.['OD10']?.baseRate || 6300,
    q.additionalFees.dropFeePerPoint,
    q.additionalFees.waitingFeePerHour,
    q.additionalFees.toll,
    q.additionalFees.porter,
    q.additionalFees.dryIce || 0,
    q.specialConditions?.join(', ') || '',
  ]);

  const ws = XLSX.utils.aoa_to_sheet([headers, ...rows]);
  ws['!cols'] = [
    { wch: 32 }, { wch: 12 }, { wch: 14 }, { wch: 14 },
    { wch: 14 }, { wch: 14 }, { wch: 14 },
    { wch: 12 }, { wch: 12 }, { wch: 12 },
    { wch: 18 }, { wch: 20 }, { wch: 12 }, { wch: 12 }, { wch: 12 }, { wch: 40 },
  ];

  XLSX.utils.book_append_sheet(wb, ws, 'Quotation_Rules');
  XLSX.writeFile(wb, 'Quotation_Master_Template_2026.xlsx');
}

/**
 * Generate and trigger download of Rate Card Master Data
 */
export function downloadRateCardMasterExcel() {
  const wb = XLSX.utils.book_new();

  const addSheetForTruck = (sheetName: string, card: any) => {
    const bracketHeaders = card.brackets.map((b: any) => b.label);
    const headers = ['Location Match', 'Province', ...bracketHeaders];

    const rows = card.rows.map((r: any) => [
      r.location,
      r.province,
      ...card.brackets.map((b: any) => r.rates[b.key] || 0),
    ]);

    const ws = XLSX.utils.aoa_to_sheet([headers, ...rows]);
    ws['!cols'] = [{ wch: 28 }, { wch: 18 }, ...card.brackets.map(() => ({ wch: 12 }))];
    XLSX.utils.book_append_sheet(wb, ws, sheetName);
  };

  addSheetForTruck('RateCard_4W', INITIAL_RATE_CARD_4W);
  addSheetForTruck('RateCard_6W', INITIAL_RATE_CARD_6W);
  addSheetForTruck('RateCard_10W', INITIAL_RATE_CARD_10W);
  addSheetForTruck('RateCard_OD4', INITIAL_RATE_CARD_OD4);
  addSheetForTruck('RateCard_OD6', INITIAL_RATE_CARD_OD6);

  XLSX.writeFile(wb, 'RateCard_Standard_16Brackets.xlsx');
}

/**
 * Generate and trigger download of PTT Diesel Database Excel
 */
export function downloadDieselDatabaseExcel() {
  const wb = XLSX.utils.book_new();

  const headers = ['วันที่ (Date)', 'ราคาน้ำมันดีเซล (THB/Litre)', 'แหล่งที่มาของข้อมูล (Source)', 'บันทึกเมื่อ (Updated At)'];
  const rows = INITIAL_DIESEL_PRICES.map((d) => [
    d.date,
    d.price,
    d.source,
    d.updatedAt || '2026-09-30T17:00:00.000Z',
  ]);

  const avgPrice = Math.round((INITIAL_DIESEL_PRICES.reduce((s, c) => s + c.price, 0) / INITIAL_DIESEL_PRICES.length) * 100) / 100;

  const summaryRows = [
    [],
    ['สรุปราคาดีเซลเดือนกันยายน 2026 (Monthly Average)'],
    ['จำนวนวันในฐานข้อมูล:', `${INITIAL_DIESEL_PRICES.length} วัน`],
    ['ราคาเฉลี่ยทั้งเดือน (Average Diesel Rate):', `${avgPrice.toFixed(2)} บาท/ลิตร`],
    ['หมายเหตุ:', 'นำค่าเฉลี่ย 40.69 ฿/L ไปใช้คำนวณใน Rate Card เพื่อขจัดปัญหา Diff (ยกเว้น Siemens เรทคงที่ 38.00 ฿/L)'],
  ];

  const ws = XLSX.utils.aoa_to_sheet([headers, ...rows, ...summaryRows]);
  ws['!cols'] = [{ wch: 18 }, { wch: 28 }, { wch: 32 }, { wch: 28 }];

  XLSX.utils.book_append_sheet(wb, ws, 'PTT_Diesel_Sep2026');
  XLSX.writeFile(wb, 'PTT_Diesel_Database_Sep2026.xlsx');
}

/**
 * Generate a realistic set of 12 transportation trips for Diff Check testing
 * Includes NLC / BLC, 4W / 6W / 10W, Roland match, and clear variances
 */
export function getRealisticDiffCheckSampleTrips(): RawTripData[] {
  return [
    {
      id: 'diff-sample-1',
      issueDate: '2/9/2026',
      clearanceDate: '3/9/2026',
      consigneeShipper: 'ROLAND DIGITAL GROUP (THAILAND)',
      address: 'นิคมอุตสาหกรรมอมตะซิตี้ ชลบุรี',
      jobNo: 'GTT-D260902001',
      hawbNo: 'HAWB-001',
      mawbNo: 'MAWB-001',
      fltNo: 'TG-102',
      invoiceNo: 'INV-260901',
      dimension: '30x40x50',
      qty: 120,
      unit: 'BOX',
      gw: 2400,
      volume: 3.5,
      product: 'ELECTRONICS',
      porter: 0,
      dryIce: 0,
      actualQty: 120,
      unit1: 'BOX',
      actualGW: 2400,
      actualVolume: 3.5,
      pickUpDate: '3/9/2026',
      pickUpTime: '08:00:00',
      pickUpIn: '9/3/26 7:50',
      pickUpOut: '9/3/26 8:30',
      pickUpName: 'BANG BO LOGISTICS CENTER (BLC)',
      pickUpAddress: 'บางบ่อ สมุทรปราการ',
      pickUpProvince: 'สมุทรปราการ',
      pickUpDistrict: 'บางบ่อ',
      pickUpZone: 'บางบ่อ',
      pickUpRemark: 'รถ 6 ล้อตู้แห้ง',
      deliveryDate: '3/9/2026',
      deliveryTime: '13:30:00',
      deliveryIn: '9/3/26 13:15',
      deliveryOut: '9/3/26 14:00',
      deliveryName: 'ROLAND DIGITAL GROUP (THAILAND)',
      deliveryAddress: 'นิคมอุตสาหกรรมอมตะซิตี้ ชลบุรี',
      deliveryProvince: 'ชลบุรี',
      deliveryDistrict: 'พานทอง',
      deliveryZone: 'อมตะนคร ชลบุรี',
      deliveryRemark: 'สัญญาเฉพาะ Roland บางบ่อ',
      csName: 'MR. SARAWUT',
      businessUnit: '1005 CLC2 BLC',
      orderType: 'Charter-Domestics',
      subContractor: 'SJD Transport',
      truckSite: 'BLC-DC',
      truckNo: '70-8812',
      driverName: 'วิชัย สุขใจ',
      truckType: '6W/Single Unit', // AW
      truckCharge: 4200, // AX - Branch Sent Rate
      transportSite: 'BLC-DC',
      tripStartDate: '9/3/26 8:00',
      tripStatus: 'FinishTrip',
      backhaul: 'No',
      tripNo: 'TRP-BLC-2609-001',
      receiver: 'K. Narong',
      tripDetailStatus: 'Completed',
      transportRemark: 'จัดส่งเรียบร้อย',
      tripCreateDate: '9/2/26 17:00',
      tripCreatedBy: 'SanyaDTG',
      haulType: 'Direct',
      closingRemark: 'ปิดรอบแล้ว',
      planRemark: '-',
      confirmOrderBy: 'Customer Care',
      customerRef2: 'REF-BLC-01',
      omsOrderNumber: 'OMS-98125',
      zipCode: '20160',
      confirmOrderDate: '9/2/26 16:00',
      eRunningNo: 'ERN-26090001',
      branch: 'บางบ่อ',
      customerQuotedRate: 4200,
    },
    {
      id: 'diff-sample-2',
      issueDate: '3/9/2026',
      clearanceDate: '4/9/2026',
      consigneeShipper: 'AJITRADE (THAILAND) CO.,LTD.',
      address: '487/1 ถนนศรีอยุธยา แขวงถนนพญาไท เขตราชเทวี กรุงเทพฯ',
      jobNo: 'GTT-D260903002',
      hawbNo: 'HAWB-002',
      mawbNo: 'MAWB-002',
      fltNo: 'TG-105',
      invoiceNo: 'INV-260902',
      dimension: '20x25x30',
      qty: 150,
      unit: 'CTN',
      gw: 2250,
      volume: 2.25,
      product: 'FOOD',
      porter: 2,
      dryIce: 0,
      actualQty: 150,
      unit1: 'CTN',
      actualGW: 2250,
      actualVolume: 2.25,
      pickUpDate: '4/9/2026',
      pickUpTime: '09:00:00',
      pickUpIn: '9/4/26 8:40',
      pickUpOut: '9/4/26 9:30',
      pickUpName: 'YUSEN LOGISTICS (THAILAND) CO.,LTD (NLC)',
      pickUpAddress: 'คลองหนึ่ง คลองหลวง ปทุมธานี',
      pickUpProvince: 'ปทุมธานี',
      pickUpDistrict: 'คลองหลวง',
      pickUpZone: 'นิคมอุตสาหกรรมนวนคร',
      pickUpRemark: 'จองรถ 4 ล้อ',
      deliveryDate: '4/9/2026',
      deliveryTime: '14:00:00',
      deliveryIn: '9/4/26 13:45',
      deliveryOut: '9/4/26 14:30',
      deliveryName: 'AJITRADE (THAILAND) CO.,LTD.',
      deliveryAddress: 'ถนนศรีอยุธยา ราชเทวี กรุงเทพฯ',
      deliveryProvince: 'กรุงเทพมหานคร',
      deliveryDistrict: 'ราชเทวี',
      deliveryZone: 'พญาไท',
      deliveryRemark: 'ส่งเอกสารตัวจริงครบชุด',
      csName: 'MS. NATTAPORN',
      businessUnit: '1004 CLC1 NLC',
      orderType: 'Charter-Domestics',
      subContractor: 'GTT Fleet',
      truckSite: 'NLC-DC',
      truckNo: '1ฒฮ-4821',
      driverName: 'สมพงษ์ ใจมั่น',
      truckType: '4W/Single Unit', // AW
      truckCharge: 3280, // AX - Branch Sent Rate
      transportSite: 'NLC-DC',
      tripStartDate: '9/4/26 8:40',
      tripStatus: 'FinishTrip',
      backhaul: 'No',
      tripNo: 'TRP-NLC-2609-002',
      receiver: 'K. Wiparat',
      tripDetailStatus: 'Completed',
      transportRemark: 'จัดส่งเรียบร้อย',
      tripCreateDate: '9/3/26 17:00',
      tripCreatedBy: 'SanyaDTG',
      haulType: 'Direct',
      closingRemark: 'ปิดรอบแล้ว',
      planRemark: '-',
      confirmOrderBy: 'Customer Care',
      customerRef2: 'REF-NLC-02',
      omsOrderNumber: 'OMS-98120',
      zipCode: '10400',
      confirmOrderDate: '9/3/26 17:30',
      eRunningNo: 'ERN-26090002',
      branch: 'นวนคร',
      customerQuotedRate: 3280,
    },
    {
      id: 'diff-sample-3',
      issueDate: '5/9/2026',
      clearanceDate: '6/9/2026',
      consigneeShipper: 'PRIMAHAM (THAILAND) CO.,LTD.',
      address: '304 Industrial Park อ.ศรีมหาโพธิ จ.ปราจีนบุรี',
      jobNo: 'GTT-D260905003',
      hawbNo: 'HAWB-003',
      mawbNo: 'MAWB-003',
      fltNo: 'SQ-901',
      invoiceNo: 'INV-260903',
      dimension: '50x50x60',
      qty: 450,
      unit: 'CTN',
      gw: 6800,
      volume: 12.5,
      product: 'CHILLED FOOD',
      porter: 2,
      dryIce: 20,
      actualQty: 450,
      unit1: 'CTN',
      actualGW: 6800,
      actualVolume: 12.5,
      pickUpDate: '6/9/2026',
      pickUpTime: '07:00:00',
      pickUpIn: '9/6/26 6:45',
      pickUpOut: '9/6/26 7:45',
      pickUpName: 'YUSEN LOGISTICS (THAILAND) CO.,LTD (NLC)',
      pickUpAddress: 'คลองหนึ่ง คลองหลวง ปทุมธานี',
      pickUpProvince: 'ปทุมธานี',
      pickUpDistrict: 'คลองหลวง',
      pickUpZone: 'นวนคร',
      pickUpRemark: 'รถ 10 ล้อตู้เย็นควบคุมอุณหภูมิ',
      deliveryDate: '6/9/2026',
      deliveryTime: '15:00:00',
      deliveryIn: '9/6/26 14:30',
      deliveryOut: '9/6/26 15:30',
      deliveryName: 'PRIMAHAM (THAILAND) CO.,LTD.',
      deliveryAddress: '304 Industrial Park อ.ศรีมหาโพธิ จ.ปราจีนบุรี',
      deliveryProvince: 'ปราจีนบุรี',
      deliveryDistrict: 'ศรีมหาโพธิ',
      deliveryZone: 'ศรีมหาโพธิ',
      deliveryRemark: 'รักษาอุณหภูมิ -18C สาขารวมค่าจุดส่งเพิ่ม 500฿',
      csName: 'MS. NATTAPORN',
      businessUnit: '1004 CLC1 NLC',
      orderType: 'Charter-Domestics',
      subContractor: 'GTT Fleet',
      truckSite: 'NLC-DC',
      truckNo: '71-5544',
      driverName: 'อนันต์ สมบูรณ์',
      truckType: '10W/Single Unit', // AW
      truckCharge: 7000, // AX - Branch Sent Rate (Diff +500฿ drop fee)
      transportSite: 'NLC-DC',
      tripStartDate: '9/6/26 7:00',
      tripStatus: 'FinishTrip',
      backhaul: 'No',
      tripNo: 'TRP-NLC-2609-003',
      receiver: 'K. Prasert',
      tripDetailStatus: 'Completed',
      transportRemark: 'ตรวจรับครบถ้วน',
      tripCreateDate: '9/5/26 18:00',
      tripCreatedBy: 'SanyaDTG',
      haulType: 'Direct',
      closingRemark: 'ปิดรอบแล้ว',
      planRemark: '-',
      confirmOrderBy: 'Customer Care',
      customerRef2: 'REF-NLC-03',
      omsOrderNumber: 'OMS-98130',
      zipCode: '25140',
      confirmOrderDate: '9/5/26 16:30',
      eRunningNo: 'ERN-26090003',
      branch: 'นวนคร',
      customerQuotedRate: 7000,
    },
    {
      id: 'diff-sample-4',
      issueDate: '7/9/2026',
      clearanceDate: '8/9/2026',
      consigneeShipper: 'THAI UNION GROUP PCL',
      address: '72/1 หมู่ 7 ถนนเศรษฐกิจ 1 ต.ท่าทราย อ.เมือง สมุทรสาคร',
      jobNo: 'GTT-D260907004',
      hawbNo: 'HAWB-004',
      mawbNo: 'MAWB-004',
      fltNo: 'TG-201',
      invoiceNo: 'INV-260904',
      dimension: '40x40x40',
      qty: 200,
      unit: 'BOX',
      gw: 3200,
      volume: 4.8,
      product: 'SEAFOOD',
      porter: 1,
      dryIce: 0,
      actualQty: 200,
      unit1: 'BOX',
      actualGW: 3200,
      actualVolume: 4.8,
      pickUpDate: '8/9/2026',
      pickUpTime: '08:30:00',
      pickUpIn: '9/8/26 8:15',
      pickUpOut: '9/8/26 9:00',
      pickUpName: 'BANG BO LOGISTICS CENTER (BLC)',
      pickUpAddress: 'บางบ่อ สมุทรปราการ',
      pickUpProvince: 'สมุทรปราการ',
      pickUpDistrict: 'บางบ่อ',
      pickUpZone: 'บางบ่อ',
      pickUpRemark: 'รถ 6 ล้อตู้แห้ง',
      deliveryDate: '8/9/2026',
      deliveryTime: '13:00:00',
      deliveryIn: '9/8/26 12:45',
      deliveryOut: '9/8/26 13:30',
      deliveryName: 'THAI UNION GROUP PCL',
      deliveryAddress: 'ต.ท่าทราย อ.เมือง สมุทรสาคร',
      deliveryProvince: 'สมุทรสาคร',
      deliveryDistrict: 'เมืองสมุทรสาคร',
      deliveryZone: 'เมืองสมุทรสาคร',
      deliveryRemark: 'สาขาเบิกค่าน้ำมันส่วนต่าง 180 บาท',
      csName: 'MR. SARAWUT',
      businessUnit: '1005 CLC2 BLC',
      orderType: 'Charter-Domestics',
      subContractor: 'SJD Transport',
      truckSite: 'BLC-DC',
      truckNo: '70-9921',
      driverName: 'สุรชัย มีสุข',
      truckType: '6W/Single Unit', // AW
      truckCharge: 4680, // AX - Branch Sent Rate (Diff +180฿)
      transportSite: 'BLC-DC',
      tripStartDate: '9/8/26 8:30',
      tripStatus: 'FinishTrip',
      backhaul: 'No',
      tripNo: 'TRP-BLC-2609-004',
      receiver: 'K. Somchai',
      tripDetailStatus: 'Completed',
      transportRemark: 'จัดส่งเรียบร้อย',
      tripCreateDate: '9/7/26 17:00',
      tripCreatedBy: 'SanyaDTG',
      haulType: 'Direct',
      closingRemark: 'ปิดรอบแล้ว',
      planRemark: '-',
      confirmOrderBy: 'Customer Care',
      customerRef2: 'REF-BLC-04',
      omsOrderNumber: 'OMS-98135',
      zipCode: '74000',
      confirmOrderDate: '9/7/26 16:00',
      eRunningNo: 'ERN-26090004',
      branch: 'บางบ่อ',
      customerQuotedRate: 4680,
    },
    {
      id: 'diff-sample-5',
      issueDate: '9/9/2026',
      clearanceDate: '10/9/2026',
      consigneeShipper: 'TOYOTA DAIHATSU ENGINEERING',
      address: 'นิคมอุตสาหกรรมนวนคร ปทุมธานี',
      jobNo: 'GTT-D260909005',
      hawbNo: 'HAWB-005',
      mawbNo: 'MAWB-005',
      fltNo: 'NH-847',
      invoiceNo: 'INV-260905',
      dimension: '35x35x35',
      qty: 90,
      unit: 'CTN',
      gw: 1500,
      volume: 2.1,
      product: 'AUTO PARTS',
      porter: 0,
      dryIce: 0,
      actualQty: 90,
      unit1: 'CTN',
      actualGW: 1500,
      actualVolume: 2.1,
      pickUpDate: '10/9/2026',
      pickUpTime: '10:00:00',
      pickUpIn: '9/10/26 9:45',
      pickUpOut: '9/10/26 10:30',
      pickUpName: 'YUSEN LOGISTICS (THAILAND) CO.,LTD (NLC)',
      pickUpAddress: 'คลองหนึ่ง คลองหลวง ปทุมธานี',
      pickUpProvince: 'ปทุมธานี',
      pickUpDistrict: 'คลองหลวง',
      pickUpZone: 'นวนคร',
      pickUpRemark: 'รถ 4 ล้อ',
      deliveryDate: '10/9/2026',
      deliveryTime: '16:00:00',
      deliveryIn: '9/10/26 15:30',
      deliveryOut: '9/10/26 16:30',
      deliveryName: 'TOYOTA DAIHATSU ENGINEERING',
      deliveryAddress: 'นิคมนวนคร คลองหนึ่ง ปทุมธานี',
      deliveryProvince: 'ปทุมธานี',
      deliveryDistrict: 'คลองหลวง',
      deliveryZone: 'นวนคร',
      deliveryRemark: 'คนขับรอโหลดสินค้าเกิน 3 ชม. สาขาเบิกค่ารอ 500฿',
      csName: 'MS. NATTAPORN',
      businessUnit: '1004 CLC1 NLC',
      orderType: 'Charter-Domestics',
      subContractor: 'GTT Fleet',
      truckSite: 'NLC-DC',
      truckNo: '1ฒฮ-9901',
      driverName: 'เกษม ทรงกลด',
      truckType: '4W/Single Unit', // AW
      truckCharge: 3780, // AX - Branch Sent Rate (Diff +500฿ OT waiting)
      transportSite: 'NLC-DC',
      tripStartDate: '9/10/26 10:00',
      tripStatus: 'FinishTrip',
      backhaul: 'No',
      tripNo: 'TRP-NLC-2609-005',
      receiver: 'K. Somkiat',
      tripDetailStatus: 'Completed',
      transportRemark: 'จัดส่งเรียบร้อย',
      tripCreateDate: '9/9/26 18:00',
      tripCreatedBy: 'SanyaDTG',
      haulType: 'Direct',
      closingRemark: 'ปิดรอบแล้ว',
      planRemark: '-',
      confirmOrderBy: 'Customer Care',
      customerRef2: 'REF-NLC-05',
      omsOrderNumber: 'OMS-98140',
      zipCode: '12120',
      confirmOrderDate: '9/9/26 17:00',
      eRunningNo: 'ERN-26090005',
      branch: 'นวนคร',
      customerQuotedRate: 3780,
    },
    {
      id: 'diff-sample-6',
      issueDate: '11/9/2026',
      clearanceDate: '12/9/2026',
      consigneeShipper: 'SIEMENS MOBILITY LIMITED',
      address: 'อาคารสินธร ถนนวิทยุ ลุมพินี ปทุมวัน กรุงเทพฯ',
      jobNo: 'GTT-D260911006',
      hawbNo: 'HAWB-006',
      mawbNo: 'MAWB-006',
      fltNo: 'LH-772',
      invoiceNo: 'INV-260906',
      dimension: '45x45x50',
      qty: 60,
      unit: 'BOX',
      gw: 1800,
      volume: 3.2,
      product: 'ELECTRICAL EQUIPMENT',
      porter: 1,
      dryIce: 0,
      actualQty: 60,
      unit1: 'BOX',
      actualGW: 1800,
      actualVolume: 3.2,
      pickUpDate: '12/9/2026',
      pickUpTime: '09:00:00',
      pickUpIn: '9/12/26 8:40',
      pickUpOut: '9/12/26 9:30',
      pickUpName: 'BANG BO LOGISTICS CENTER (BLC)',
      pickUpAddress: 'บางบ่อ สมุทรปราการ',
      pickUpProvince: 'สมุทรปราการ',
      pickUpDistrict: 'บางบ่อ',
      pickUpZone: 'บางบ่อ',
      pickUpRemark: 'รถ 6 ล้อตู้แห้ง',
      deliveryDate: '12/9/2026',
      deliveryTime: '14:00:00',
      deliveryIn: '9/12/26 13:45',
      deliveryOut: '9/12/26 14:30',
      deliveryName: 'SIEMENS MOBILITY LIMITED',
      deliveryAddress: 'ถนนวิทยุ ลุมพินี ปทุมวัน กรุงเทพฯ',
      deliveryProvince: 'กรุงเทพมหานคร',
      deliveryDistrict: 'ปทุมวัน',
      deliveryZone: 'ปทุมวัน',
      deliveryRemark: 'สัญญาน้ำมันคงที่ 38.00 ฿/L',
      csName: 'MR. SARAWUT',
      businessUnit: '1005 CLC2 BLC',
      orderType: 'Charter-Domestics',
      subContractor: 'SJD Transport',
      truckSite: 'BLC-DC',
      truckNo: '70-5511',
      driverName: 'ชัชวาล รุ่งโรจน์',
      truckType: '6W/Single Unit', // AW
      truckCharge: 4200, // AX - Branch Sent Rate (Match)
      transportSite: 'BLC-DC',
      tripStartDate: '9/12/26 9:00',
      tripStatus: 'FinishTrip',
      backhaul: 'No',
      tripNo: 'TRP-BLC-2609-006',
      receiver: 'K. Klaus',
      tripDetailStatus: 'Completed',
      transportRemark: 'จัดส่งเรียบร้อย',
      tripCreateDate: '9/11/26 17:00',
      tripCreatedBy: 'SanyaDTG',
      haulType: 'Direct',
      closingRemark: 'ปิดรอบแล้ว',
      planRemark: '-',
      confirmOrderBy: 'Customer Care',
      customerRef2: 'REF-BLC-06',
      omsOrderNumber: 'OMS-98145',
      zipCode: '10330',
      confirmOrderDate: '9/11/26 16:00',
      eRunningNo: 'ERN-26090006',
      branch: 'บางบ่อ',
      customerQuotedRate: 4200,
    },
    {
      id: 'diff-sample-7',
      issueDate: '13/9/2026',
      clearanceDate: '14/9/2026',
      consigneeShipper: 'CARGILL MEATS (THAILAND) LIMITED',
      address: 'อ.โชคชัย จ.นครราชสีมา',
      jobNo: 'GTT-D260913007',
      hawbNo: 'HAWB-007',
      mawbNo: 'MAWB-007',
      fltNo: 'TG-602',
      invoiceNo: 'INV-260907',
      dimension: '60x60x60',
      qty: 500,
      unit: 'CTN',
      gw: 9500,
      volume: 18.0,
      product: 'FROZEN POULTRY',
      porter: 2,
      dryIce: 50,
      actualQty: 500,
      unit1: 'CTN',
      actualGW: 9500,
      actualVolume: 18.0,
      pickUpDate: '14/9/2026',
      pickUpTime: '06:00:00',
      pickUpIn: '9/14/26 5:45',
      pickUpOut: '9/14/26 6:45',
      pickUpName: 'YUSEN LOGISTICS (THAILAND) CO.,LTD (NLC)',
      pickUpAddress: 'คลองหลวง ปทุมธานี',
      pickUpProvince: 'ปทุมธานี',
      pickUpDistrict: 'คลองหลวง',
      pickUpZone: 'นวนคร',
      pickUpRemark: 'รถ 10 ล้อตู้เย็น',
      deliveryDate: '14/9/2026',
      deliveryTime: '15:30:00',
      deliveryIn: '9/14/26 15:00',
      deliveryOut: '9/14/26 16:00',
      deliveryName: 'CARGILL MEATS (THAILAND) LIMITED',
      deliveryAddress: 'อ.โชคชัย จ.นครราชสีมา',
      deliveryProvince: 'นครราชสีมา',
      deliveryDistrict: 'โชคชัย',
      deliveryZone: 'โชคชัย',
      deliveryRemark: 'ทริปทางไกลนครราชสีมา',
      csName: 'MS. NATTAPORN',
      businessUnit: '1004 CLC1 NLC',
      orderType: 'Charter-Domestics',
      subContractor: 'GTT Fleet',
      truckSite: 'NLC-DC',
      truckNo: '72-1144',
      driverName: 'บุญมี มีโชค',
      truckType: '10W/Single Unit', // AW
      truckCharge: 6500, // AX - Branch Sent Rate (Match)
      transportSite: 'NLC-DC',
      tripStartDate: '9/14/26 6:00',
      tripStatus: 'FinishTrip',
      backhaul: 'No',
      tripNo: 'TRP-NLC-2609-007',
      receiver: 'K. Somkiat',
      tripDetailStatus: 'Completed',
      transportRemark: 'จัดส่งเรียบร้อย',
      tripCreateDate: '9/13/26 18:00',
      tripCreatedBy: 'SanyaDTG',
      haulType: 'Direct',
      closingRemark: 'ปิดรอบแล้ว',
      planRemark: '-',
      confirmOrderBy: 'Customer Care',
      customerRef2: 'REF-NLC-07',
      omsOrderNumber: 'OMS-98150',
      zipCode: '30190',
      confirmOrderDate: '9/13/26 17:00',
      eRunningNo: 'ERN-26090007',
      branch: 'นวนคร',
      customerQuotedRate: 6500,
    },
    {
      id: 'diff-sample-8',
      issueDate: '15/9/2026',
      clearanceDate: '15/9/2026',
      consigneeShipper: 'DENSO (THAILAND) CO.,LTD.',
      address: 'นิคมอุตสาหกรรมเวลโกรว์ ฉะเชิงเทรา',
      jobNo: 'GTT-D260915008',
      hawbNo: 'HAWB-008',
      mawbNo: 'MAWB-008',
      fltNo: 'TG-108',
      invoiceNo: 'INV-260908',
      dimension: '30x30x30',
      qty: 50,
      unit: 'BOX',
      gw: 800,
      volume: 1.5,
      product: 'AUTO PARTS',
      porter: 0,
      dryIce: 0,
      actualQty: 50,
      unit1: 'BOX',
      actualGW: 800,
      actualVolume: 1.5,
      pickUpDate: '15/9/2026',
      pickUpTime: '11:00:00',
      pickUpIn: '9/15/26 10:45',
      pickUpOut: '9/15/26 11:30',
      pickUpName: 'BANG BO LOGISTICS CENTER (BLC)',
      pickUpAddress: 'บางบ่อ สมุทรปราการ',
      pickUpProvince: 'สมุทรปราการ',
      pickUpDistrict: 'บางบ่อ',
      pickUpZone: 'บางบ่อ',
      pickUpRemark: 'ลูกค้ายกเลิกคำสั่งซื้อก่อนเข้ารับสินค้า',
      deliveryDate: '15/9/2026',
      deliveryTime: '15:00:00',
      deliveryIn: '-',
      deliveryOut: '-',
      deliveryName: 'DENSO (THAILAND) CO.,LTD.',
      deliveryAddress: 'นิคมอุตสาหกรรมเวลโกรว์ ฉะเชิงเทรา',
      deliveryProvince: 'ฉะเชิงเทรา',
      deliveryDistrict: 'บางปะกง',
      deliveryZone: 'เวลโกรว์',
      deliveryRemark: 'ยกเลิกคำสั่งซื้อ (Cancelled Trip - 0 บาท)',
      csName: 'MR. SARAWUT',
      businessUnit: '1005 CLC2 BLC',
      orderType: 'Charter-Domestics',
      subContractor: 'SJD Transport',
      truckSite: 'BLC-DC',
      truckNo: '70-8812',
      driverName: 'วิชัย สุขใจ',
      truckType: '4W/Single Unit', // AW
      truckCharge: 0, // AX - Cancelled Trip 0 บาท
      transportSite: 'BLC-DC',
      tripStartDate: '9/15/26 11:00',
      tripStatus: 'Cancelled',
      backhaul: 'No',
      tripNo: 'TRP-BLC-2609-008',
      receiver: '-',
      tripDetailStatus: 'Cancelled',
      transportRemark: 'ยกเลิกโดยลูกค้าก่อนเข้ารับ',
      tripCreateDate: '9/15/26 10:00',
      tripCreatedBy: 'SanyaDTG',
      haulType: 'Direct',
      closingRemark: 'ยกเลิก (0 บาท)',
      planRemark: '-',
      confirmOrderBy: 'Customer Care',
      customerRef2: 'REF-BLC-08',
      omsOrderNumber: 'OMS-98155',
      zipCode: '24180',
      confirmOrderDate: '9/15/26 09:30',
      eRunningNo: 'ERN-26090008',
      branch: 'บางบ่อ',
      customerQuotedRate: 0,
    },
  ];
}

